trigger: none

schedules:
- cron: "0 23 * * *"   # 11 PM UTC (adjust later)
  displayName: Shutdown daily
  branches:
    include:
      - main
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-conn-shutdown'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Fetching VMs..."

      az vm list --query "[].{name:name, rg:resourceGroup}" -o tsv | while read name rg
      do
        echo "Stopping VM: $name in $rg"
        az vm stop --name $name --resource-group $rg
      done
